name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix git safe directory
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Clean build (safe)
      run: |
        buildozer android clean || true

    - name: Build APK (non-interactive)
      run: |
        yes | buildozer -v android debug

