name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix git safe directory
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Install dependencies (safe CI env)
      run: |
        export PIP_BREAK_SYSTEM_PACKAGES=1
        pip install --upgrade pip
        pip install cython

    - name: Build APK (non-interactive)
      run: |
        export BUILDOZER_ALLOW_ROOT=1
        yes | buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
