name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix permissions
      run: |
        git config --global --add safe.directory /__w/*

    - name: Clean build (optional)
      run: |
        buildozer android clean || true

    - name: Build APK (no interaction)
      run: |
        export PIP_BREAK_SYSTEM_PACKAGES=1
        yes | buildozer -v android debug
